[[ $- != *i* ]] && return

fpath=($HOME/.config/zsh/completions $HOME/.config/zsh/themes $HOME/.config/zsh/functions /usr/local/share/zsh/site-functions $fpath )
path=(/usr/local/sbin /usr/local/bin /usr/bin /bin /usr/sbin /sbin)
if [[ -n ${#commands[pyenv]} ]]; then
  export PYENV_ROOT=$HOME/.pyenv
  source <(pyenv init -)
  source <(pyenv virtualenv-init -)
fi
if (( ${#commands[rbenv]} > 0 )); then
  export RBENV_ROOT=$HOME/.rbenv
  source <(rbenv init -)
  export PROJECT_HOME=~/Development
fi
if (( ${#commands[nodenv]} > 0 )); then
  source <(nodenv init -)
fi
path=("$HOME/bin" $path)

autoload $HOME/.config/zsh/functions/[^_]*(.:t)
autoload -U promptinit && promptinit
for f in $HOME/.config/zsh/*.zsh(on); do
    . $f
done

alias less=$PAGER
alias zless=$PAGER 
autoload zmv

autoload -U edit-command-line
zle -N edit-command-line

hash -d github=$HOME/github

#autoload complist
if (( UID )); then
    autoload -U compinit;
    compinit
fi

source <(ssh-keyring)

typeset -U fpath path
prompt powerline
